### ISSUE TITLE
Command stop to work

### ISSUE THREAD

**Issue by pimpin** [cbumgard/GitCommitMsg#14]
Hi.
Thanks for this awesome tool I've installed 2 weeks ago.
It suddenly stop to work for me.
I've tried to uninstall and reinstall with Package controll. But nothing appends when running the command.

I've also tried to use the Command Palet (`cmd+shift+p`) to launch it.

---

**My conf :**
Mac OS : 10.7.5
ST : 2.0.2 build 2221
git in path : git version 1.7.12.4 (Apple Git-37)

**Comment by cbumgard** [comment]
Ah darn. Looks like yesterday's merge of a pull request related to threading must have broken it. It does work on ST3 however. I'll look into it.

**Comment by jobedom** [comment]
Sorry about this. I'm installing ST2 right now so I will take a look too.

**Comment by cbumgard** [comment]
Thanks! Looking at http://www.sublimetext.com/docs/3/porting_guide.html it's because only set_timeout() was thread safe in ST2 whereas in ST3 all methods are thread safe.

**Comment by jobedom** [comment]
I'm sending a pull request with a temporary fix. I refactored the meat of the plugin into a new function, so Python 3 (ST3) uses threading and Python 2 (ST2) does not. 

Thanks for the link. I'm reading the porting guide and will try to make a proper fix.

**Comment by cbumgard** [comment]
Verified on ST2 & ST3 on Mac OS X. Closing this particular issue.

**Comment by pimpin** [comment]
Thank you.
I confirm the fixed status.
