### ISSUE TITLE
Add to command pallete

### ISSUE THREAD

**Issue by aleemb** [cbumgard/GitCommitMsg#19]
This is a great plugin but not exactly one that would get routinely. The last two times I had to use the plugin, I had to look up the docs to find the shortcut because I didn't remember it.

Could you please add it to the command palette that would make it much easier to use.

**Comment by cbumgard** [comment]
Thanks - it actually does have command palette integration. Could you please make sure you have the latest version? It was committed here: https://github.com/cbumgard/GitCommitMsg/pull/8.
