### ISSUE TITLE
What do you do after installing? 

### ISSUE THREAD

**Issue by ghost** [cbumgard/GitCommitMsg#22]
I don't see any change to my file view, menubar, contextual dialog, or sidebar in ST3 on Yosemite. Could a brief summary or screenshot be added to the readme? Thank you.

**Comment by dkwolfe4** [comment]
use the following key combinations to see last commit message.

Mac: Default keybinding is Command+Shift+m
Linux/Windows: Default keybinding is Alt+Shift+m

Alternatively use the cmd palette to invoke.

**Comment by ghost** [comment]
Thank you.
