### ISSUE TITLE
Doesn't appear to be in Package Control

### ISSUE THREAD

**Issue by wpillar** [cbumgard/GitCommitMsg#3]
I can't find it listed on the website or within the list of repositories in Sublime?

**Comment by aleemb** [comment]
+1
Just saw this on HN and imagine a lot of others reading there will want to install it via package control.

**Comment by gabeio** [comment]
+1
agreed it is not present in the install packages

**Comment by Fishrock123** [comment]
+1

**Comment by cbames** [comment]
If you do Package Control: Add Repository and then enter https://github.com/cbumgard/GitCommitMsg.git it will show up in package control, and install everything for you.

**Comment by aprescott** [comment]
@cbames can you add it to the central repository of available packages? There is a guide available at https://sublime.wbond.net/docs/developers. This way a custom repository isn't necessary.

**Comment by aprescott** [comment]
@cbames whoops, that meant to go to @cbumgard!

**Comment by octatone** [comment]
+1

**Comment by thecodejunkie** [comment]
+1 on this. The README file doesn't mention the need to add a custom repository, but suggests it's available in the main one.

**Comment by cbumgard** [comment]
Hi all, I submitted a pull request to the package control repo last night when I pushed the project, but looks like there will be a short lag before it's accepted. I'll repost here once it's on there.

**Comment by neilernst** [comment]
It is there now.

**Comment by cbumgard** [comment]
Thanks everyone
