### ISSUE TITLE
Not working on Windows 8

### ISSUE THREAD

**Issue by arelangi** [cbumgard/GitCommitMsg#4]
Installed the package manually . Git is added to the path. The console shows that the command is executed, but no results are shown. Running the same command directly on git bash shows the result

![image](https://f.cloud.github.com/assets/1182529/2128068/5e8a2036-9276-11e3-945b-e203f8be91e5.png)

**Comment by cbumgard** [comment]
I'm guessing it's the "awk" command. I'm installing Windows now in Parallels so I can test it out.

**Comment by thecodejunkie** [comment]
I was trying this on Windows 7 x64 and experienced the same. `awk` is not available on Windows, you can get it by installing [cygwin](http://www.cygwin.com/) or [msysgit](https://code.google.com/p/msysgit/) but even then GitCommitMsg won't work as you don't get access to the commands from the ordinary command line, but have to run Bash.

**Comment by cbumgard** [comment]
Thanks for the info - going to see if there's a workaround without the need for installing anything extra. If you think of something though please do create a pull-request.

**Comment by jobedom** [comment]
I created a pull request fixing this. Thanks for the plugin.

**Comment by cbumgard** [comment]
Great fix, thanks
