### ISSUE TITLE
Add a .sublime-commands file so that it shows up in the command palette

### ISSUE THREAD

**Issue by timmfin** [cbumgard/GitCommitMsg#7]
I'm unlikely to remember the keyboard shortcut, so it would be great if this command showed up in the command palette (the command list that shows up when I press `cmd+shift+p`. 

It looks like you can get that to happen by adding a `.sublime-commands` file to the package.

**Comment by cbumgard** [comment]
Added in the last pull-request merged

**Comment by timmfin** [comment]
Perfect, thanks!
